#!/usr/bin/env bash

github() {
  mkdir -p .github/workflows
}

gitignore() {
  echo node_modules/ >> .gitignore
}

webhint() {
  npm install --save-dev hint@6.0.x
  curl -O https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css/.hintrc
}

stylelint() {
  npm install --save-dev stylelint@13.3.x stylelint-scss@3.17.x stylelint-config-standard@20.0.x stylelint-csstree-validator
  curl -O https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css/.stylelintrc.json
}

rubocop() {
  echo gem 'rubocop', '~>0.81.0' >> Gemfile
  bundle install
  curl -O https://raw.githubusercontent.com/microverseinc/linters-config/master/ruby/.rubocop.yml
}

if [ -z "$1" ]
then
  echo "Use the --help flag to checkout the available options."
  exit 1
elif [ $1 == --html ]
then
  github
  curl https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css/.github/workflows/linters.yml -o .github/workflows/linters.yml
  gitignore
  webhint
  stylelint
elif [ $1 == --ruby ]
then
  github
  curl https://raw.githubusercontent.com/microverseinc/linters-config/master/ruby/.github/workflows/linters.yml -o .github/workflows/linters.yml
elif [ $1 == --rails ]
then
  github
  curl https://raw.githubusercontent.com/microverseinc/linters-config/master/ror/.github/workflows/linters.yml -o .github/workflows/linters.yml
  gitignore
  rubocop
  stylelint
fi
