#!/usr/bin/env bash

github() {
  mkdir -p .github/workflows
  curl "https://raw.githubusercontent.com/microverseinc/linters-config/master/${1}/.github/workflows/linters.yml" -o .github/workflows/linters.yml
}

gitignore() {
  echo node_modules/ >> .gitignore
}

webhint() {
  npm install --save-dev hint@6.0.x
  curl -O https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css/.hintrc
}

stylelint() {
  npm install --save-dev stylelint@13.3.x stylelint-scss@3.17.x stylelint-config-standard@20.0.x stylelint-csstree-validator
  curl -O "https://raw.githubusercontent.com/microverseinc/linters-config/master/${1}/.stylelintrc.json"
}

rubocop() {
  echo gem \'rubocop\', \'~\>0.81.0\' >> Gemfile
  bundle install
  curl -O "https://raw.githubusercontent.com/microverseinc/linters-config/master/${1}/.rubocop.yml"
}

eslint() {
  if [ $1 == javascript ]
  then
    npm install --save-dev eslint@6.8.x eslint-config-airbnb-base@14.1.x eslint-plugin-import@2.20.x babel-eslint@10.1.x
  elif [ $1 == react-redux ]
  then
    npm install --save-dev eslint@7.11.x eslint-config-airbnb@18.1.x eslint-plugin-import@2.22.x eslint-plugin-jsx-a11y@6.2.x eslint-plugin-react@7.20.x eslint-plugin-react-hooks@2.5.x babel-eslint@10.1.x --legacy-peer-deps
  fi
  curl -O "https://raw.githubusercontent.com/microverseinc/linters-config/master/${1}/.eslintrc.json"
}

if [ -z "$1" ]
then
  echo "Use the --help flag to checkout the available options."
  exit 1
elif [ $1 == --help ]
then
  echo "--html                 setup html&css linters"
  echo "--ruby                 setup ruby linters"
  echo "--rails                setup rails linters"
  echo "--javascript           setup javascript linters"
  echo "--react                setup react-redux linters"
elif [ $1 == --html ]
then
  github html-css
  gitignore
  webhint
  stylelint html-css
elif [ $1 == --ruby ]
then
  github ruby
  rubocop ruby
elif [ $1 == --rails ]
then
  github ror
  rubocop ror
  stylelint ror
elif [ $1 == --javascript ]
then
  github javascript
  gitignore
  eslint javascript
  stylelint javascript
elif [ $1 == --react ]
then
  github react-redux
  eslint react-redux
  stylelint react-redux
else
  echo "Invalid option. Use the --help flag to checkout all the options."
  exit 1
fi
